<?php

namespace Container1z0xnMD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlanningGeneratorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PlanningGenerator' shared autowired service.
     *
     * @return \App\Service\PlanningGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PlanningGenerator.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\PlanningGenerator'])) {
            return $container->privates['App\\Service\\PlanningGenerator'];
        }

        return $container->privates['App\\Service\\PlanningGenerator'] = new \App\Service\PlanningGenerator(($container->privates['App\\Repository\\GroupeRepository'] ?? $container->load('getGroupeRepositoryService')), ($container->privates['App\\Repository\\PersonnelRepository'] ?? $container->load('getPersonnelRepositoryService')), $a);
    }
}
