<?php

namespace ContainerXPZ7ZOG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1XLc_V7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1XLc.V7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1XLc.V7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'generator' => ['services', 'App\\Service\\PlanningGenerator', 'getPlanningGeneratorService', true],
        ], [
            'em' => '?',
            'generator' => 'App\\Service\\PlanningGenerator',
        ]);
    }
}
