<?php

namespace ContainerXPZ7ZOG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SihLUsAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SihLUsA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SihLUsA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'personnel' => ['privates', '.errored..service_locator.SihLUsA.App\\Entity\\Personnel', NULL, 'Cannot autowire service ".service_locator.SihLUsA": it needs an instance of "App\\Entity\\Personnel" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'personnel' => 'App\\Entity\\Personnel',
        ]);
    }
}
