<?php

namespace ContainerXAU520x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7qrnM9DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7qrnM9D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7qrnM9D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'generator' => ['services', 'App\\Service\\PlanningGenerator', 'getPlanningGeneratorService', true],
        ], [
            'generator' => 'App\\Service\\PlanningGenerator',
        ]);
    }
}
