<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCAlJTnf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCAlJTnf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCAlJTnf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCAlJTnf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCAlJTnf\App_KernelDevDebugContainer([
    'container.build_hash' => 'CAlJTnf',
    'container.build_id' => '1ac21503',
    'container.build_time' => 1747820962,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCAlJTnf');
