<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPZ7ZOG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPZ7ZOG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXPZ7ZOG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXPZ7ZOG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXPZ7ZOG\App_KernelDevDebugContainer([
    'container.build_hash' => 'XPZ7ZOG',
    'container.build_id' => '52f6655b',
    'container.build_time' => 1747935654,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPZ7ZOG');
