<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFcYndP0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFcYndP0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFcYndP0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFcYndP0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFcYndP0\App_KernelDevDebugContainer([
    'container.build_hash' => 'FcYndP0',
    'container.build_id' => 'f80318d2',
    'container.build_time' => 1747687328,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFcYndP0');
