<?php

namespace ContainerXhnDhei;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DUfnokAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dUfnokA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dUfnokA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PlanningController::list' => ['privates', '.service_locator..vn4bjL', 'get_ServiceLocator__Vn4bjLService', true],
            'App\\Controller\\PlanningController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PlanningController::voirTempsTravail' => ['privates', '.service_locator.yZHtf.2', 'get_ServiceLocator_YZHtf_2Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PlanningController:list' => ['privates', '.service_locator..vn4bjL', 'get_ServiceLocator__Vn4bjLService', true],
            'App\\Controller\\PlanningController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\PlanningController:voirTempsTravail' => ['privates', '.service_locator.yZHtf.2', 'get_ServiceLocator_YZHtf_2Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PlanningController::list' => '?',
            'App\\Controller\\PlanningController::new' => '?',
            'App\\Controller\\PlanningController::voirTempsTravail' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PlanningController:list' => '?',
            'App\\Controller\\PlanningController:new' => '?',
            'App\\Controller\\PlanningController:voirTempsTravail' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
